// ==UserScript==
// @name         SimplifiedChineseDeepRacer
// @namespace    SimplifiedChineseDeepRacer
// @version      1.0.1
// @description  Translates DeepRacer console into Simplified Chinese
// @author       jdaped
// @match        https://*.console.aws.amazon.com/deepracer/*
// @updateURL    https://jeremypedersen.com/resources/tampermonkey/SimplifiedChineseDeepRacer.user.js
// @downloadURL  https://jeremypedersen.com/resources/tampermonkey/SimplifiedChineseDeepRacer.user.js
// ==/UserScript==

// This timeout is a "hack" to wait for the page to load
// TODO: Find a more elegant way to wait for page load
setTimeout(function () {

    var replaceArray = [
		[/=LEN(B2)/gi, 'Organizations can activate multi-user mode to sponsor and manage multiple racer profiles under one AWS account ID. Costs related to sponsored racers’ training hours and storage are billed to the sponsor’s account. Sponsors can view the usage of their sponsored profiles in the dashboard and can pause sponsorship of profiles at any time. This feature is particularly useful for organizations wishing to plan large events.'],
		[/=LEN(B3)/gi, 'The Pro Division is for racers who have earned a top 10% time trial result from the previous month. Racers in the Pro Division earn bigger rewards and can compete in the monthly finale for qualifying seats in the yearly AWS re:Invent Championship Cup. Pro Division racers compete in more complex racing formats, such as head-to-head or object avoidance, which require stereo camera or LiDAR sensor configurations.'],
		[/=LEN(B4)/gi, 'The Virtual League Golden Badge signifies the current Pro Division monthly finale title holder. The badge is displayed on the winning racer’s profile and next to their racer name on Pro Division leaderboards for as long as that racer tops the leaderboard. If a new racer takes the title in a following race, the former titleholder’s badge becomes silver to celebrate that racer’s status as a past title holder.'],
		[/=LEN(B5)/gi, 'The new league structure splits the current Virtual Circuit monthly leaderboard into two skill-based divisions, each with their own prizes to maintain a high level of competitiveness in the League. The Open Division is where all racers begin their ML learning journey. Participation is rewarded each month with new digital rewards. Open Division racers compete in the time trial format.'],
		[/=LEN(B6)/gi, 'Community project that leverages OpenCV image-processing capabilities to detect a mouse in the image from an infrared camera mounted on the DeepRacer. The infrared camera allows the RoboCat to detect the mouse in the dark and scare it away using a pre-configured action space with 3 actions (move forward if a mouse is detected, move back after previous action, and remain stationary).'],
		[/=LEN(B7)/gi, 'Congratulations to I-Lee from the National Yang Ming Chiao Tung University in Taiwan and the over 150,000 developers from over 160 countries who participated in the 2022 AWS DeepRacer League! Compete in the 2023 season to win a trip to Las Vegas and a chance to earn over \$20,000\! Start training your model now to secure your spot when League opens on March 1, 2023.'],
		[/=LEN(B8)/gi, 'With a multi-user account setup, organizers \(such as account administrators\) can provide participants access to AWS DeepRacer under their account ID. They can also monitor spending on training and storage, enable and disable training, and view and manage models for every user in their account from the AWS DeepRacer console.'],
		[/=LEN(B9)/gi, 'Mimics a real-world car that starts and stops at traffic lights and stop signs. The logic for identifying different colors in traffic signals and detect stop signs was developed by combining various computer vision capabilities, including OpenCV image-processing functions and object-detection machine learning models.'],
		[/=LEN(B10)/gi, 'you will receive 10 free hours to train or evaluate models and 5GB of free storage during your first month. This is enough to train your first time-trial model, evaluate it, tune it, and then enter it into the AWS DeepRacer League. This offer is valid for 30 days after you have used the service for the first time.'],
		[/=LEN(B11)/gi, 'Multi-racer competition (driving slower if another DeepRacer is in front of the car or overtaking other cars using the LIDAR sensor), autonomous vehicle, using AI for safety and perception (training the car to stop when a person or animal walks in front of it and detecting and staying within the bounds of a lane).'],
		[/=LEN(B12)/gi, 'is a component of the AWS DeepRacer console, where you can choose to customize your agent with supported sensor units, an action space, a neural network topology, and a customized appearance for training RL models to run on a DeepRacer vehicle. In other words, you build or maintain your agent in'],
		[/=LEN(B13)/gi, 'The Pro division is for racers who have earned a top 10% time trial result from the previous month. Racers in the Pro Division can earn bigger rewards and win qualifying seats for the 2022 AWS re:Invent Championship Cup. Pro Division racers compete in object avoidance and head-to-head formats.'],
		[/=LEN(B14)/gi, 'The Pro Division monthly finale takes place on the AWS DeepRacer official Twitch channel. Winners automatically secure a spot in the Championship Cup and a trip to AWS re:Invent to compete for \$10,000 in AWS credits, and an F1 experience or a \$20,000 value ML education sponsorship.'],
		[/=LEN(B15)/gi, 'Learn to deploy an object detection model that enables the AWS DeepRacer device to identify and follow an object. Extend this sample project by modifying the code to recognize other objects for your use case. Bring your own custom model, navigation logic, and add-on hardware'],
		[/=LEN(B16)/gi, 'The new AWS DeepRacer League structure splits the current Virtual Circuit monthly leaderboard into two skill-based divisions, Pro and Open. Each division offers its own racing formats and opportunities for prizes to maintain a high level of overall competitiveness.'],
		[/=LEN(B17)/gi, 'Use a series of QR codes as waypoints to navigate the AWS DeepRacer around a custom path. Create your own custom path by placing the basic waypoint codes as a sequence along the track or encode additional instructions in them to invent new applications.'],
		[/=LEN(B18)/gi, 'Welcome to the world’s first global autonomous racing league, open to anyone. Race for prizes, glory, and a chance to advance to the AWS DeepRacer Championship Cup at re:Invent. Get on the track to compete online in the monthly Virtual Circuit races.'],
		[/=LEN(B19)/gi, 'Winners of the Pro Division monthly finale automatically secure a spot in the Championship Cup and a trip to AWS re:Invent to compete for \$10,000 in AWS credits, as well as an F1 experience or a \$20,000-value ML education sponsorship.'],
		[/=LEN(B20)/gi, 'In this project, use the AWS DeepRacer car to draw a map with SLAM (Simultaneous Localization and Mapping), a technique for creating a map of an environment by estimating a device’s current location as it moves through a space.'],
		[/=LEN(B21)/gi, 'Pro Division participants receive the same customization given to Open Division participants plus 1 exclusive Pro car customization per month. Example rewards include new body shells, custom paint colors, and designer wraps.'],
		[/=LEN(B22)/gi, 'Configure your vehicle with one or more sensors, choose a neural network topology, and customize the action space to meet your racing criteria. Customize your vehicle's appearance for personalized visualization in training.'],
		[/=LEN(B23)/gi, 'The AWS DeepRacer Free Tier provides 10 free hours to train or evaluate models and 5GB of free storage during your first 30 days to create, train, evaluate, and submit your model to the Virtual Circuit.'],
		[/=LEN(B24)/gi, 'pane, you can view the racer profiles you are sponsoring. You can edit usage quotas for training hours, delete sponsored users' models, as well as pause and resume sponsorship of selected users.'],
		[/=LEN(B25)/gi, 'Reinforcement Learning \(RL\) is the Machine Learning technique which drives AWS DeepRacer. Learn the basics of RL to create and optimize your models to compete in the AWS DeepRacer League.'],
		[/=LEN(B26)/gi, 'Host a race privately or broadcast it publicly to machine learning enthusiasts around the globe. Invite your colleagues, classmates, or friends by sharing a race invitation link.'],
		[/=LEN(B27)/gi, 'All racers begin their ML learning journey in the Open Division. Open Division racers compete in the time trial format and receive monthly digital rewards for participation.'],
		[/=LEN(B28)/gi, 'Request a 60 minute online or in-person workshop on reinforcement learning with AWS DeepRacer. Participants learn how to create, train, and improve their models.'],
		[/=LEN(B29)/gi, 'Identify the most dominant topics associated with your products, policies, events, and brands by launching this solution that uses Amazon Rekognition.'],
		[/=LEN(B30)/gi, 'Open Division participants receive 1 car customization per month. Example rewards include new body shells, custom paint colors, and designer wraps.'],
		[/=LEN(B31)/gi, 'Open Division monthly winners are promoted to the Pro Division where they can compete for the Pro Division title and Virtual League Golden Badge.'],
		[/=LEN(B32)/gi, 'With AWS DeepRacer, you are charged for storage, and training and evaluation jobs. Model training and evaluation is charged at a flat fee of \$'],
		[/=LEN(B33)/gi, 'Demo Amazon Personalize for free with the highly interactive Magic Movie Machine to generate personalized movie recommendations in real time.'],
		[/=LEN(B34)/gi, 'Develop navigation systems for home robots, such as vacuum cleaners, a fleet of mobile warehouse robots, or parking a self-driving car.'],
		[/=LEN(B35)/gi, 'Build fun applications (use the DeepRacer as a digital pet or follow an object) or industrial prototypes (warehousing, manufacturing).'],
		[/=LEN(B36)/gi, 'pane, you can view a summary of estimated spending based on the number of sponsored users and their training hours as well as storage.'],
		[/=LEN(B37)/gi, 'and paintjobs for competing each month. Top the ranks in open division to earn exclusive DeepRacer merchandise and advance to the'],
		[/=LEN(B38)/gi, 'in the world and a chance to advance and win the AWS DeepRacer Championship Cup. Earn new digital rewards such as custom shells'],
		[/=LEN(B39)/gi, 'The AWS DeepRacer League has over \*5x more\* chances to win prizes than ever before. Race for prizes and glory from anywhere'],
		[/=LEN(B40)/gi, 'pros, where you can win big prizes such as an AWS DeepRacer Evo device and a chance for an expenses paid trip to re:Invent to'],
		[/=LEN(B41)/gi, 'Disabling multi-user mode will prevent any new profile creation and training under the DeepRacer administrator's AWS account.'],
		[/=LEN(B42)/gi, 'a variety of practical business problems from robotics automation, to finance, to game optimization, and autonomous vehicles.'],
		[/=LEN(B43)/gi, 'Submit your trained model to the virtual leaderboard to enter the AWS DeepRacer League, the world’s first global autonomous'],
		[/=LEN(B44)/gi, 'your autonomous racing models, built with reinforcement learning. Train your models and get ready to race in the League.'],
		[/=LEN(B45)/gi, 'Simply follow the steps in the console to build, train and evaluate your model and enter the AWS DeepRacer League. With'],
		[/=LEN(B46)/gi, 'AWS DeepRacer has an integrated simulation environment hosted on the AWS Cloud for experimentation and optimization of'],
		[/=LEN(B47)/gi, 'racing league, driven by reinforcement learning. Compete and connect with racers from 6 continents and 115 countries.'],
		[/=LEN(B48)/gi, 'guidance on building reinforcement learning models. Reinforcement learning is a branch of machine learning, ideal for'],
		[/=LEN(B49)/gi, 'AWS DeepRacer allows developers of any skill level to get started with machine learning with hands-on tutorials and'],
		[/=LEN(B50)/gi, 'Code, create, and collaborate with our GitHub community to make your AWS DeepRacer more than the sum of its parts.'],
		[/=LEN(B51)/gi, 'Get hands-on with a fully autonomous 1\/18th scale race car driven by reinforcement learning, 3D racing simulator,'],
		[/=LEN(B52)/gi, 'Take this free 90 minute training and certification course to start your machine learning journey with DeepRacer.'],
		[/=LEN(B53)/gi, 'Try out this beginner tutorial to learn how to use Amazon Comprehend to analyze and derive insights from text.'],
		[/=LEN(B54)/gi, 'Launch this solution to learn how you can use Amazon Polly and Amazon Lex to create a multi-faceted chatbot.'],
		[/=LEN(B55)/gi, 'Build your model, evaluate its performance on a virtual track, and then compete in the AWS DeepRacer League.'],
		[/=LEN(B56)/gi, 'A community race is a private virtual race that you can share with your fellow AWS DeepRacer friends. Select'],
		[/=LEN(B57)/gi, 'To make new applications using the open-source code, your AWS DeepRacer device needs to be on Ubuntu 20.04.'],
		[/=LEN(B58)/gi, 'Use our email template to invite users to participate in fast-paced racing action with AWS DeepRacer.'],
		[/=LEN(B59)/gi, 'DeepDriver by Jochem Lugtenburg, Developer at Relive, Former DeepRacer Championship Cup finalist'],
		[/=LEN(B60)/gi, 'Student community races are available to all students with a AWS DeepRacer Student account.'],
		[/=LEN(B61)/gi, 'Note: These robotics projects are not required to participate in the AWS DeepRacer League.'],
		[/=LEN(B62)/gi, 'Get the latest AWS DeepRacer news and share tips and tricks with our community of racers.'],
		[/=LEN(B63)/gi, 'Race on your own terms! Organize a private LIVE virtual event for your friends and peers.'],
		[/=LEN(B64)/gi, 'Use multi-user mode to provide and manage AWS Player accounts for multiple participants.'],
		[/=LEN(B65)/gi, 'Try AWS DeepRacer Arcade for mobile, a free browser-based game that teaches ML basics.'],
		[/=LEN(B66)/gi, 'Learn how to use Amazon Textract to extract text and structured data from a document.'],
		[/=LEN(B67)/gi, 'Learn how to translate text between languages in the cloud using Amazon Translate.'],
		[/=LEN(B68)/gi, 'Try out these experiences to learn new ML skills and more. Explore new experiences'],
		[/=LEN(B69)/gi, 'Read instructions to find out if your AWS DeepRacer is already using Ubuntu 20.04'],
		[/=LEN(B70)/gi, 'Create your first Amazon Lex chatbot that provides a few basic banking functions.'],
		[/=LEN(B71)/gi, 'Evaluate and compare your model's performance with new evaluation capabilities.'],
		[/=LEN(B72)/gi, 'Work with core AWS services such as AWS Amplify and more to create a web app.'],
		[/=LEN(B73)/gi, 'This can take a few minutes, but you can build your ML skills while you wait'],
		[/=LEN(B74)/gi, 'Admin will keep access to all resources \(models, leaderboards, and cars\).'],
		[/=LEN(B75)/gi, 'Ask questions, exchange tips, and share best practices with fellow racers.'],
		[/=LEN(B76)/gi, 'Create machine learning projects with Jupyter notebooks in your browser.'],
		[/=LEN(B77)/gi, 'Community races are available to all customers through the AWS Console.'],
		[/=LEN(B78)/gi, 'page is a curation of ML projects and experiences for you to try out.'],
		[/=LEN(B79)/gi, 'to create a community race for student racers or any type of racer.'],
		[/=LEN(B80)/gi, 'Open from 4:18 AM on December 8 until 7:59 AM on February 1 GMT+8.'],
		[/=LEN(B81)/gi, 'Check out our favorite projects or contribute your own on GitHub.'],
		[/=LEN(B82)/gi, 'Open from 8:00 AM on February 1 until 7:59 AM on March 1 GMT+8.'],
		[/=LEN(B83)/gi, 'Enter the DeepRacer League Virtual Circuit for a chance to win.'],
		[/=LEN(B84)/gi, 'AWS Player profiles still exist and can be sponsored by another'],
		[/=LEN(B85)/gi, 'Step 1: Take a crash course on Reinforcement Learning \(10min\)'],
		[/=LEN(B86)/gi, 'Try out demos, tutorials, and courses to build your ML skills.'],
		[/=LEN(B87)/gi, 'Looking to learn new ML skills after racing in AWS DeepRacer?'],
		[/=LEN(B88)/gi, 'to meet the requirements of your autonomous driving solution.'],
		[/=LEN(B89)/gi, 'Race takes place in AWS DeepRacer Student. Students need an'],
		[/=LEN(B90)/gi, 'Try out these experiences to learn new ML skills and more.'],
		[/=LEN(B91)/gi, 'Create one-click solutions for machine learning use cases.'],
		[/=LEN(B92)/gi, 'for video streaming of virtual simulation footage, Amazon'],
		[/=LEN(B93)/gi, 'Create machine learning projects using Jupyter notebooks'],
		[/=LEN(B94)/gi, 'Demos, tutorials, and courses to learn new ML skills.'],
		[/=LEN(B95)/gi, 'The fastest way to get rolling with machine learning'],
		[/=LEN(B96)/gi, 'Can you beat Championship Cup winner I-Lee in 2023'],
		[/=LEN(B97)/gi, 'Quickly evaluate models in the 3D racing simulator'],
		[/=LEN(B98)/gi, 'Join an AWS DeepRacer League Virtual Circuit Race'],
		[/=LEN(B99)/gi, 'Welcome to the 2023 AWS DeepRacer community races'],
		[/=LEN(B100)/gi, 'AWS DeepRacer was built on existing AWS services'],
		[/=LEN(B101)/gi, 'Participate in monthly races to win new awards.'],
		[/=LEN(B102)/gi, 'for reinforcement learning model training, AWS'],
		[/=LEN(B103)/gi, 'Neural Compute Stick 2 for faster processing'],
		[/=LEN(B104)/gi, 'Request an AWS DeepRacer workshop \(5 mins\)'],
		[/=LEN(B105)/gi, 'Create your own DeepRacer LIVE virtual race'],
		[/=LEN(B106)/gi, 'Event creator can not take part in the race'],
		[/=LEN(B107)/gi, 'Competing in the next virtual circuit race'],
		[/=LEN(B108)/gi, 're:Invent 2022 Warm Up race participation'],
		[/=LEN(B109)/gi, 'Create a free web app using core services'],
		[/=LEN(B110)/gi, 'Disable multi-user account mode \(1 min\)'],
		[/=LEN(B111)/gi, 'Racing divisions concepts and terminology'],
		[/=LEN(B112)/gi, 'Profiles monitoring will be deactivated.'],
		[/=LEN(B113)/gi, 'Event creator can take part in the race'],
		[/=LEN(B114)/gi, 'to provide the racing simulator, Amazon'],
		[/=LEN(B115)/gi, 'Dive deeper into reinforcement learning'],
		[/=LEN(B116)/gi, 'Get started with reinforcement learning'],
		[/=LEN(B117)/gi, 'Get personalized movie recommendations'],
		[/=LEN(B118)/gi, 'How to join a PRO\/OPEN Division race'],
		[/=LEN(B119)/gi, 'Analyze and derive insights from text'],
		[/=LEN(B120)/gi, 'Join an AWS DeepRacer community race'],
		[/=LEN(B121)/gi, 'AWS DeepRacer integrates with Amazon'],
		[/=LEN(B122)/gi, 'Compete in the global Racing League'],
		[/=LEN(B123)/gi, 'Welcome to the 2023 Virtual Circuit'],
		[/=LEN(B124)/gi, 'AWS DeepRacer or AWS DeepRacer Evo'],
		[/=LEN(B125)/gi, 'Training and evaluation hours used'],
		[/=LEN(B126)/gi, 'Software and hardware for robotics'],
		[/=LEN(B127)/gi, 'Get rolling with machine learning'],
		[/=LEN(B128)/gi, 'Join the AWS DeepRacer community'],
		[/=LEN(B129)/gi, 'compete in the Championship Cup.'],
		[/=LEN(B130)/gi, 'Race takes place in AWS Console'],
		[/=LEN(B131)/gi, 'to invent your own application.'],
		[/=LEN(B132)/gi, 'AWS DeepRacer digital training'],
		[/=LEN(B133)/gi, 'Other admin actions \(5 mins\)'],
		[/=LEN(B134)/gi, 'AWS DeepRacer Student account'],
		[/=LEN(B135)/gi, 'for model storage, and Amazon'],
		[/=LEN(B136)/gi, 'Automate content translation'],
		[/=LEN(B137)/gi, 'Download physical car model'],
		[/=LEN(B138)/gi, 'View instructions on GitHub'],
		[/=LEN(B139)/gi, 'The fastest way to learn ML'],
		[/=LEN(B140)/gi, 'Up to 2 competition formats'],
		[/=LEN(B141)/gi, 'Race in the Virtual Circuit'],
		[/=LEN(B142)/gi, 'Order an AWS DeepRacer EVO'],
		[/=LEN(B143)/gi, 'Multi-user mode is enabled'],
		[/=LEN(B144)/gi, 'Connect with the community'],
		[/=LEN(B145)/gi, 'DeepRacer League overview'],
		[/=LEN(B146)/gi, 'LIVE monthly Twitch races'],
		[/=LEN(B147)/gi, 'and global racing league.'],
		[/=LEN(B148)/gi, 'Prerequisites \(10 mins\)'],
		[/=LEN(B149)/gi, 'Race for prizes and glory'],
		[/=LEN(B150)/gi, 'Virtual Circuit divisions'],
		[/=LEN(B151)/gi, 'Your journey starts here'],
		[/=LEN(B152)/gi, 'Automate data extraction'],
		[/=LEN(B153)/gi, 'View invitation template'],
		[/=LEN(B154)/gi, 'How AWS DeepRacer works'],
		[/=LEN(B155)/gi, 'Community Slack channel'],
		[/=LEN(B156)/gi, 'Estimated spend \(USD\)'],
		[/=LEN(B157)/gi, 'Disable multi-user mode'],
		[/=LEN(B158)/gi, 'and model storage is \$'],
		[/=LEN(B159)/gi, 'Create a community race'],
		[/=LEN(B160)/gi, 'Neural network topology'],
		[/=LEN(B161)/gi, 'Explore new experiences'],
		[/=LEN(B162)/gi, 'Step 2: Create a model'],
		[/=LEN(B163)/gi, 'Try a robotics project'],
		[/=LEN(B164)/gi, 'Set up multi-user mode'],
		[/=LEN(B165)/gi, 'Enable multi-user mode'],
		[/=LEN(B166)/gi, 'Student community race'],
		[/=LEN(B167)/gi, 'Create community races'],
		[/=LEN(B168)/gi, 'Reinforcement learning'],
		[/=LEN(B169)/gi, 'AWS DeepRacer Pricing'],
		[/=LEN(B170)/gi, 'Multi-user management'],
		[/=LEN(B171)/gi, 'Initializing training'],
		[/=LEN(B172)/gi, 'Open Division rewards'],
		[/=LEN(B173)/gi, 'Features and benefits'],
		[/=LEN(B174)/gi, 'Win trips and prizes'],
		[/=LEN(B175)/gi, 'Time trial race type'],
		[/=LEN(B176)/gi, 'Pro Division rewards'],
		[/=LEN(B177)/gi, 'AWS Virtual Circuit'],
		[/=LEN(B178)/gi, 'Identify hot topics'],
		[/=LEN(B179)/gi, 'AWS Developer forum'],
		[/=LEN(B180)/gi, 'to access the race.'],
		[/=LEN(B181)/gi, 'Try computer vision'],
		[/=LEN(B182)/gi, 'Recommended add-on:'],
		[/=LEN(B183)/gi, 'Classic race format'],
		[/=LEN(B184)/gi, 'Up to 3 race types'],
		[/=LEN(B185)/gi, 'Build a banker bot'],
		[/=LEN(B186)/gi, 'Your racer profile'],
		[/=LEN(B187)/gi, 'Your racer profile'],
		[/=LEN(B188)/gi, 'Live monthly races'],
		[/=LEN(B189)/gi, 'About PRO Division'],
		[/=LEN(B190)/gi, 'Start your engines'],
		[/=LEN(B191)/gi, 'Request a workshop'],
		[/=LEN(B192)/gi, 'Sponsorship status'],
		[/=LEN(B193)/gi, 'Resume sponsorship'],
		[/=LEN(B194)/gi, 'Gigabyte per month'],
		[/=LEN(B195)/gi, 'Learning resources'],
		[/=LEN(B196)/gi, 'Buy AWS DeepRacer'],
		[/=LEN(B197)/gi, 'Joining DeepRacer'],
		[/=LEN(B198)/gi, 'Try generative AI'],
		[/=LEN(B199)/gi, 'Start your engine'],
		[/=LEN(B200)/gi, 'Race entries open'],
		[/=LEN(B201)/gi, 'Build new vehicle'],
		[/=LEN(B202)/gi, 'Arcade for mobile'],
		[/=LEN(B203)/gi, 'Pause sponsorship'],
		[/=LEN(B204)/gi, 'Download software'],
		[/=LEN(B205)/gi, 'Featured projects'],
		[/=LEN(B206)/gi, 'Read instructions'],
		[/=LEN(B207)/gi, 'Community project'],
		[/=LEN(B208)/gi, 'About the league'],
		[/=LEN(B209)/gi, 'for log capture.'],
		[/=LEN(B210)/gi, 'Start the course'],
		[/=LEN(B211)/gi, 'Required add-on:'],
		[/=LEN(B212)/gi, 'Upcoming new car'],
		[/=LEN(B213)/gi, 'Set usage quotas'],
		[/=LEN(B214)/gi, 'Machine Learning'],
		[/=LEN(B215)/gi, 'Related services'],
		[/=LEN(B216)/gi, 'Championship cup'],
		[/=LEN(B217)/gi, 'Build a Q&A bot'],
		[/=LEN(B218)/gi, 'Completed races'],
		[/=LEN(B219)/gi, 'Developer guide'],
		[/=LEN(B220)/gi, 'Community Races'],
		[/=LEN(B221)/gi, 'Sponsored users'],
		[/=LEN(B222)/gi, 'Digital rewards'],
		[/=LEN(B223)/gi, 'Number of users'],
		[/=LEN(B224)/gi, 'Gap to fastest'],
		[/=LEN(B225)/gi, 'Device needed:'],
		[/=LEN(B226)/gi, 'Pricing \(US\)'],
		[/=LEN(B227)/gi, '61 race tracks'],
		[/=LEN(B228)/gi, '12 race tracks'],
		[/=LEN(B229)/gi, 'Rules & prizes'],
		[/=LEN(B230)/gi, 'Next challenge'],
		[/=LEN(B231)/gi, 'Community race'],
		[/=LEN(B232)/gi, 'days remaining'],
		[/=LEN(B233)/gi, 'Community blog'],
		[/=LEN(B234)/gi, 'Skill building'],
		[/=LEN(B235)/gi, 'Submit project'],
		[/=LEN(B236)/gi, 'AWS DeepRacer'],
		[/=LEN(B237)/gi, 'AWS DeepRacer'],
		[/=LEN(B238)/gi, 'AWS Free Tier'],
		[/=LEN(B239)/gi, 'Monitor usage'],
		[/=LEN(B240)/gi, 'Current usage'],
		[/=LEN(B241)/gi, 'Project ideas'],
		[/=LEN(B242)/gi, 'Tips & tricks'],
		[/=LEN(B243)/gi, 'Create a race'],
		[/=LEN(B244)/gi, 'Race location'],
		[/=LEN(B245)/gi, 'Racing League'],
		[/=LEN(B246)/gi, 'Creation time'],
		[/=LEN(B247)/gi, 'Create a race'],
		[/=LEN(B248)/gi, 'Model storage'],
		[/=LEN(B249)/gi, 'Delete models'],
		[/=LEN(B250)/gi, 'View projects'],
		[/=LEN(B251)/gi, 'Prizing email'],
		[/=LEN(B252)/gi, 'Open Division'],
		[/=LEN(B253)/gi, 'Race division'],
		[/=LEN(B254)/gi, 'Documentation'],
		[/=LEN(B255)/gi, 'Storage used'],
		[/=LEN(B256)/gi, '10 minutes ·'],
		[/=LEN(B257)/gi, '30 minutes ·'],
		[/=LEN(B258)/gi, 'Notebook lab'],
		[/=LEN(B259)/gi, 'Become a PRO'],
		[/=LEN(B260)/gi, 'Manage races'],
		[/=LEN(B261)/gi, 'Import model'],
		[/=LEN(B262)/gi, 'Invite users'],
		[/=LEN(B263)/gi, 'Queued usage'],
		[/=LEN(B264)/gi, 'Racing since'],
		[/=LEN(B265)/gi, 'PRO Division'],
		[/=LEN(B266)/gi, 'Create model'],
		[/=LEN(B267)/gi, 'Pro Division'],
		[/=LEN(B268)/gi, 'Get hardware'],
		[/=LEN(B269)/gi, 'Race details'],
		[/=LEN(B270)/gi, 'Winter Open'],
		[/=LEN(B271)/gi, '5 minutes ·'],
		[/=LEN(B272)/gi, 'Create race'],
		[/=LEN(B273)/gi, 'Get started'],
		[/=LEN(B274)/gi, 'Your garage'],
		[/=LEN(B275)/gi, 'Your models'],
		[/=LEN(B276)/gi, 'Manage tags'],
		[/=LEN(B277)/gi, 'Your models'],
		[/=LEN(B278)/gi, 'Date joined'],
		[/=LEN(B279)/gi, 'Mod vehicle'],
		[/=LEN(B280)/gi, 'Get started'],
		[/=LEN(B281)/gi, 'Leaderboard'],
		[/=LEN(B282)/gi, 'Description'],
		[/=LEN(B283)/gi, 'What is it'],
		[/=LEN(B284)/gi, 'Copy to S3'],
		[/=LEN(B285)/gi, 'Race again'],
		[/=LEN(B286)/gi, 'Start now.'],
		[/=LEN(B287)/gi, 'Racer name'],
		[/=LEN(B288)/gi, 'Race dates'],
		[/=LEN(B289)/gi, 'Shell type'],
		[/=LEN(B290)/gi, 'Learn more'],
		[/=LEN(B291)/gi, 'Max models'],
		[/=LEN(B292)/gi, '(optional)'],
		[/=LEN(B293)/gi, 'Quick demo'],
		[/=LEN(B294)/gi, 'Time trial'],
		[/=LEN(B295)/gi, 'Earned for'],
		[/=LEN(B296)/gi, 'Race track'],
		[/=LEN(B297)/gi, 'Max usage'],
		[/=LEN(B298)/gi, '2 hours ·'],
		[/=LEN(B299)/gi, 'Your rank'],
		[/=LEN(B300)/gi, 'Race type'],
		[/=LEN(B301)/gi, 'Sensor(s)'],
		[/=LEN(B302)/gi, 'Read blog'],
		[/=LEN(B303)/gi, 'September'],
		[/=LEN(B304)/gi, 'Resources'],
		[/=LEN(B305)/gi, 'Algorithm'],
		[/=LEN(B306)/gi, '1 hour ·'],
		[/=LEN(B307)/gi, 'Play now'],
		[/=LEN(B308)/gi, 'November'],
		[/=LEN(B309)/gi, 'December'],
		[/=LEN(B310)/gi, 'February'],
		[/=LEN(B311)/gi, 'OVERVIEW'],
		[/=LEN(B312)/gi, 'Workshop'],
		[/=LEN(B313)/gi, 'Tutorial'],
		[/=LEN(B314)/gi, 'Country'],
		[/=LEN(B315)/gi, 'October'],
		[/=LEN(B316)/gi, 'Sensors'],
		[/=LEN(B317)/gi, 'January'],
		[/=LEN(B318)/gi, 'Actions'],
		[/=LEN(B319)/gi, 'Summary'],
		[/=LEN(B320)/gi, 'Awarded'],
		[/=LEN(B321)/gi, 'Add-on'],
		[/=LEN(B322)/gi, 'Level:'],
		[/=LEN(B323)/gi, 'August'],
		[/=LEN(B324)/gi, 'Garage'],
		[/=LEN(B325)/gi, 'Novice'],
		[/=LEN(B326)/gi, 'Models'],
		[/=LEN(B327)/gi, 'Delete'],
		[/=LEN(B328)/gi, 'Status'],
		[/=LEN(B329)/gi, 'Awards'],
		[/=LEN(B330)/gi, 'Badges'],
		[/=LEN(B331)/gi, 'In the'],
		[/=LEN(B332)/gi, 'Alias'],
		[/=LEN(B333)/gi, 'March'],
		[/=LEN(B334)/gi, 'April'],
		[/=LEN(B335)/gi, 'Forum'],
		[/=LEN(B336)/gi, 'Setup'],
		[/=LEN(B337)/gi, 'Clone'],
		[/=LEN(B338)/gi, 'hours'],
		[/=LEN(B339)/gi, 'Info'],
		[/=LEN(B340)/gi, 'Wins'],
		[/=LEN(B341)/gi, 'June'],
		[/=LEN(B342)/gi, 'July'],
		[/=LEN(B343)/gi, 'Name'],
		[/=LEN(B344)/gi, 'team'],
		[/=LEN(B345)/gi, 'Edit'],
		[/=LEN(B346)/gi, 'hour'],
		[/=LEN(B347)/gi, 'per'],
		[/=LEN(B348)/gi, 'May'],
		[/=LEN(B349)/gi, 'The']
    ];

    var numTerms = replaceArray.length;
    var txtWalker = document.createTreeWalker(
        document.body,
        NodeFilter.SHOW_TEXT,
        {
            acceptNode: function (node) {
                //-- Skip whitespace-only nodes
                if (node.nodeValue.trim()) {
                    return NodeFilter.FILTER_ACCEPT;
                }

                return NodeFilter.FILTER_SKIP;
            }
        },
        false
    );
    var txtNode = null;

    while (txtNode = txtWalker.nextNode()) {
        var oldTxt = txtNode.nodeValue;

        for (var J = 0; J < numTerms; J++) {
            oldTxt = oldTxt.replace(replaceArray[J][0], replaceArray[J][1]);
        }
        txtNode.nodeValue = oldTxt;
    }

}, 3000);


